apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: telegram-bots
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: telegram-bots
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      namespace: telegram-bots
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: cashtrack/mysql:1.0.11
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
              subPath: mysql
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 500Mi
          envFrom:
            - secretRef:
                name: mysql-secret
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h 127.0.0.1 -e 'SELECT 1'
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
        - name: backup
          image: cashtrack/mysql-backup:0.0.5
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: MYSQL_HOST
              value: 0.0.0.0
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-secret
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  key: S3_REGION
                  name: mysql-secret
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: S3_ENDPOINT
                  name: mysql-secret
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: S3_BUCKET
                  name: mysql-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: S3_KEY
                  name: mysql-secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: S3_SECRET
                  name: mysql-secret
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: telegram-bots
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
