version: "2.8"

server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///var/run/rr-relay.sock"
  relay: "unix:///var/run/rr-relay.sock"

http:
  address: 0.0.0.0:8090
  middleware: ["static", "headers", "gzip"]
  pool:
    max_jobs: 64
    supervisor:
      exec_ttl: 0s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php"]

logs:
  mode: production
  level: info

