apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crashers-bot-ingress
  namespace: telegram-bots
spec:
  ingressClassName: nginx
  rules:
    - host: crashers-bot.cash-track.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crashers-bot
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crashers-bot
  namespace: telegram-bots
spec:
  type: ClusterIP
  selector:
    app: crashers-bot
  ports:
    - port: 80
      targetPort: 8090
