name: release

on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    uses: cash-track/.github/.github/workflows/build.yml@main
    with:
      image: vovanms/crashers_bot_api
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    needs: build
    uses: cash-track/.github/.github/workflows/deploy.yml@main
    with:
      service: api
      post_deploy_cmds: >
        php artisan webhook:unset
        php artisan migrate --force
        php artisan webhook:set
    secrets:
      TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
